# Generated by Django 4.1.7 on 2023-05-18 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="house_number",
        ),
    ]
