# Generated by Django 4.1.7 on 2023-03-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainpage", "0002_book_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="name",
            new_name="book_name",
        ),
    ]
