# Generated by Django 4.1.7 on 2023-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0008_profile_alter_book_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Inactive",
                max_length=10,
            ),
        ),
    ]
