# Generated by Django 4.1.7 on 2023-06-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0009_book_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
    ]
