# Generated by Django 4.1.7 on 2023-06-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0010_alter_book_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("None", "None"),
                            ("Fantasy", "Fantasy"),
                            ("Adventure", "Adventure"),
                            ("Romance", "Romance"),
                            ("Detective", "Detective"),
                            ("Thriller", "Thriller"),
                            ("Historical", "Historical"),
                        ],
                        default="None",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="mainpage.genre",
            ),
        ),
    ]
