# Generated by Django 4.1.7 on 2023-06-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0011_genre_book_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Fantasy", "Fantasy"),
                    ("Adventure", "Adventure"),
                    ("Romance", "Romance"),
                    ("Detective", "Detective"),
                    ("Thriller", "Thriller"),
                    ("Historical", "Historical"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
