from django.urls import path
from .views import (
    ListBooksAPI,
    CreateBookAPI,
    UpdateBookAPI,
    RetrieveBookAPI,
    CreateOrderAPI,
    GetOrderAPI,
    ListUserInformation,
    UpdateUserInformation,
    ListUserOrders,
    ClearUserOrders,
    ListUserListedBooks,
    ListFantasyBooksAPI,
    ListThrillerBooksAPI,
    ListRomanceBooksAPI,
    ListAdventureBooksAPI,
    ListDetectiveBooksAPI,
    ListHistoricalBooksAPI,
)

urlpatterns = [
    path("books/list", ListBooksAPI.as_view(), name="ListAllBooks"),
    path("books/fantasy", ListFantasyBooksAPI.as_view(), name="ListFantasyBooks"),
    path("books/thriller", ListThrillerBooksAPI.as_view(), name="ListThrillerBooks"),
    path("books/romance", ListRomanceBooksAPI.as_view(), name="ListRomanceBooks"),
    path("books/adventure", ListAdventureBooksAPI.as_view(), name="ListAdventureBooks"),
    path("books/detective", ListDetectiveBooksAPI.as_view(), name="ListDetectiveBooks"),
    path("books/historical", ListHistoricalBooksAPI.as_view(), name="ListHistoricalBooks"),
    path("books/create", CreateBookAPI.as_view(), name="CreateBook"),
    path("books/update/<int:pk>", UpdateBookAPI.as_view(), name="UpdateBook"),
    path("books/get/<int:pk>", RetrieveBookAPI.as_view(), name="GetOneBook"),

    path("order/create/<int:pk>",
         CreateOrderAPI.as_view(),
         name="CreateOrder"),
    path("order/get/<int:pk>", GetOrderAPI.as_view(), name="GetOrder"),

    path("profile/", ListUserInformation.as_view(), name="UserProfile"),
    path("profile/update",
         UpdateUserInformation.as_view(), name="UpdateUserProfile"),
    path("profile/orders", ListUserOrders.as_view(), name="ListOrders"),
    path("profile/orders/clear",
         ClearUserOrders.as_view(), name="ClearOrders"),
    path("profile/books",
         ListUserListedBooks.as_view(), name="UserListedBooks"),
]
